// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: route/groove.proto

package route

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SymmetricKeyGenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientId  int32  `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *SymmetricKeyGenRequest) Reset() {
	*x = SymmetricKeyGenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_groove_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymmetricKeyGenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymmetricKeyGenRequest) ProtoMessage() {}

func (x *SymmetricKeyGenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_route_groove_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymmetricKeyGenRequest.ProtoReflect.Descriptor instead.
func (*SymmetricKeyGenRequest) Descriptor() ([]byte, []int) {
	return file_route_groove_proto_rawDescGZIP(), []int{0}
}

func (x *SymmetricKeyGenRequest) GetClientId() int32 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SymmetricKeyGenRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type SymmetricKeyGenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *SymmetricKeyGenResponse) Reset() {
	*x = SymmetricKeyGenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_groove_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SymmetricKeyGenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymmetricKeyGenResponse) ProtoMessage() {}

func (x *SymmetricKeyGenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_route_groove_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymmetricKeyGenResponse.ProtoReflect.Descriptor instead.
func (*SymmetricKeyGenResponse) Descriptor() ([]byte, []int) {
	return file_route_groove_proto_rawDescGZIP(), []int{1}
}

func (x *SymmetricKeyGenResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type CircuitSetupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Tag     int32  `protobuf:"varint,2,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *CircuitSetupRequest) Reset() {
	*x = CircuitSetupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_groove_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CircuitSetupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitSetupRequest) ProtoMessage() {}

func (x *CircuitSetupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_route_groove_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitSetupRequest.ProtoReflect.Descriptor instead.
func (*CircuitSetupRequest) Descriptor() ([]byte, []int) {
	return file_route_groove_proto_rawDescGZIP(), []int{2}
}

func (x *CircuitSetupRequest) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *CircuitSetupRequest) GetTag() int32 {
	if x != nil {
		return x.Tag
	}
	return 0
}

type CircuitSetupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CircuitSetupResponse) Reset() {
	*x = CircuitSetupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_groove_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CircuitSetupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircuitSetupResponse) ProtoMessage() {}

func (x *CircuitSetupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_route_groove_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircuitSetupResponse.ProtoReflect.Descriptor instead.
func (*CircuitSetupResponse) Descriptor() ([]byte, []int) {
	return file_route_groove_proto_rawDescGZIP(), []int{3}
}

func (x *CircuitSetupResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type FetchPublicKeyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *FetchPublicKeyRequest) Reset() {
	*x = FetchPublicKeyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_groove_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPublicKeyRequest) ProtoMessage() {}

func (x *FetchPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_route_groove_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*FetchPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_route_groove_proto_rawDescGZIP(), []int{4}
}

type FetchPublicKeyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *FetchPublicKeyResponse) Reset() {
	*x = FetchPublicKeyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_route_groove_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPublicKeyResponse) ProtoMessage() {}

func (x *FetchPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_route_groove_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*FetchPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_route_groove_proto_rawDescGZIP(), []int{5}
}

func (x *FetchPublicKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_route_groove_proto protoreflect.FileDescriptor

var file_route_groove_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x6f, 0x76, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x16, 0x53, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x22, 0x38, 0x0a, 0x17, 0x53, 0x79,
	0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x22, 0x41, 0x0a, 0x13, 0x43, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x53,
	0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x69, 0x72, 0x63, 0x75,
	0x69, 0x74, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x17, 0x0a, 0x15, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x37, 0x0a, 0x16, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x32, 0x50, 0x0a, 0x06, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x46, 0x0a, 0x0f, 0x53, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x12, 0x17, 0x2e, 0x53, 0x79, 0x6d, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x47, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x18, 0x2e, 0x53, 0x79, 0x6d, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x4b, 0x65, 0x79,
	0x47, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x8c, 0x01,
	0x0a, 0x06, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3d, 0x0a, 0x0c, 0x43, 0x69, 0x72, 0x63,
	0x75, 0x69, 0x74, 0x53, 0x65, 0x74, 0x75, 0x70, 0x12, 0x14, 0x2e, 0x43, 0x69, 0x72, 0x63, 0x75,
	0x69, 0x74, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15,
	0x2e, 0x43, 0x69, 0x72, 0x63, 0x75, 0x69, 0x74, 0x53, 0x65, 0x74, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0e, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x2e, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_route_groove_proto_rawDescOnce sync.Once
	file_route_groove_proto_rawDescData = file_route_groove_proto_rawDesc
)

func file_route_groove_proto_rawDescGZIP() []byte {
	file_route_groove_proto_rawDescOnce.Do(func() {
		file_route_groove_proto_rawDescData = protoimpl.X.CompressGZIP(file_route_groove_proto_rawDescData)
	})
	return file_route_groove_proto_rawDescData
}

var file_route_groove_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_route_groove_proto_goTypes = []interface{}{
	(*SymmetricKeyGenRequest)(nil),  // 0: SymmetricKeyGenRequest
	(*SymmetricKeyGenResponse)(nil), // 1: SymmetricKeyGenResponse
	(*CircuitSetupRequest)(nil),     // 2: CircuitSetupRequest
	(*CircuitSetupResponse)(nil),    // 3: CircuitSetupResponse
	(*FetchPublicKeyRequest)(nil),   // 4: FetchPublicKeyRequest
	(*FetchPublicKeyResponse)(nil),  // 5: FetchPublicKeyResponse
}
var file_route_groove_proto_depIdxs = []int32{
	0, // 0: Client.SymmetricKeyGen:input_type -> SymmetricKeyGenRequest
	2, // 1: Server.CircuitSetup:input_type -> CircuitSetupRequest
	4, // 2: Server.FetchPublicKey:input_type -> FetchPublicKeyRequest
	1, // 3: Client.SymmetricKeyGen:output_type -> SymmetricKeyGenResponse
	3, // 4: Server.CircuitSetup:output_type -> CircuitSetupResponse
	5, // 5: Server.FetchPublicKey:output_type -> FetchPublicKeyResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_route_groove_proto_init() }
func file_route_groove_proto_init() {
	if File_route_groove_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_route_groove_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymmetricKeyGenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_groove_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SymmetricKeyGenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_groove_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CircuitSetupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_groove_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CircuitSetupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_groove_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPublicKeyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_route_groove_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPublicKeyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_route_groove_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_route_groove_proto_goTypes,
		DependencyIndexes: file_route_groove_proto_depIdxs,
		MessageInfos:      file_route_groove_proto_msgTypes,
	}.Build()
	File_route_groove_proto = out.File
	file_route_groove_proto_rawDesc = nil
	file_route_groove_proto_goTypes = nil
	file_route_groove_proto_depIdxs = nil
}
